<?php

namespace AppBundle\Repository;

/**
 * TraderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraderRepository extends \Doctrine\ORM\EntityRepository
{
}
